# Generated by Django 4.1.4 on 2022-12-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_comment_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_address_details',
            name='user_id',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit_comment_details',
            name='user_id',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit_contact_details',
            name='user_id',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit_details',
            name='unit_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='unit_details',
            name='user_id',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
