# Generated by Django 4.1.4 on 2022-12-27 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_comment_dashboard', '0004_unit_address_details_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_comment_details',
            name='unit_address_details_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_comment_dashboard.unit_details'),
        ),
        migrations.DeleteModel(
            name='unit_contact_details',
        ),
    ]
