# Generated by Django 4.1.4 on 2022-12-27 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_comment_dashboard', '0005_alter_unit_comment_details_unit_address_details_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_comment_details',
            name='unit_address_details_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_comment_dashboard.unit_address_details'),
        ),
    ]
