# Generated by Django 4.1.4 on 2022-12-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_comment_dashboard', '0009_alter_unit_comment_details_unit_address_details_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_comment_details',
            name='car_type',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='unit_comment_details',
            name='remarks',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
